# Generated by Django 4.0 on 2021-12-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.EmailField(max_length=254)),
                ('text_content', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
